#%RAML 1.0
title: Example of Optional Properties
resourceTypes:
   corpResource:
      post?: # optional property
        description: Some info about <<TextAboutPost>>. # contains custom parameter
        headers:
          X-Chargeback:
            required: true
/servers:
  type:
    corpResource:
      TextAboutPost: post method # post defined which will force to define the TextAboutPost parameter
  get:
  post: # will require the X-Chargeback header
/queues:
  type: corpResource
  get:
  # will not have a post method defined which means one MUST not have to define
  # the TextAboutPost parameter
