apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: BOAT
  description: The Backbase Open API Tools is a collection of tools created to work efficiently with OpenAPI
  tags:
    - java
    - openapi
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: library
  lifecycle: production
  owner: backend-guild
