#%RAML 1.0
---
#===============================================================
# Integration API example
#===============================================================
title: Example
version: v1
baseUri: "integration-api/{version}"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
#===============================================================
#  API documentation - Overall documentation.
#===============================================================
documentation:
  - title: Example
    content: Test Schema to test an integration-api
#===============================================================
# API resource definitions
#===============================================================
/items:
  description: Retrieve all items.
  displayName: items
  uriParameters: null
  get:
    description: "Retrieve list of all items."
    responses:
      200:
        description: Test Schema
        body:
          application/json:
            schema: !include schemas/body/item.json
            example: !include examples/body/item.json