#%RAML 1.0 Library
schemas:
  ObjectWrappingException: !include common-schemas/body/object-wrapping-exception.json
types:
  XmlContent: !include common-schemas/body/funky-values.json
  TestHeadersResponseBody: !include common-schemas/body/test-headers-response.json