#%RAML 1.0 Library
  schemas:
    ObjectWrappingException: !include common-schemas/body/object-wrapping-exception.json
  types:
    PaymentCard: !include common-schemas/body/paymentcard-item.json
    PaymentCards: !include common-schemas/body/paymentcards-get.json
    TestHeadersResponseBody: !include common-schemas/body/test-headers-response.json