#%RAML 1.0 Extension
# File located at:
# /extensions/en_US/additionalResources.raml
extends: ./presentation-client-api.raml
usage: This extension defines additional resources for version 2 of the API.
version: v2
types:
 Address:
    properties:
      street: string
      city: string
    examples:
      example1:
        strict: false
        value:
          street: "sweetums"
          city: "Pawnee"
      example2:
        strict: false
        value:
          street: "copy paper"
          city: "Staples"
/wallet:
  displayName: Wallet
  /paymentcards:
    displayName: Payment Cards
    get:
      (bb.x-bb-access-control):
        resource: WALLET
        function: MANAGE_PAYMENT_CARDS
        privilege: READ_PAYMENT_CARD
      is: [traits.BadRequestError, traits.NotAcceptableError, traits.orderable: {fieldsList: nameOnCard}, traits.InternalServerError, traits.ForbiddenError, traits.UnsupportedMediaTypeError, traits.NotFoundError, traits.UnauthorizedError]
      description: "Returns available payment card details for user, optionally filtered by nameOnCard"
      queryParameters:
        nameOnCard:
          description: "Filter by the cardholder's name (case-insensitive), can be the first one or more characters of one of the words/names"
          required: false
          type: string
          example: "Smi"
        dateTimeOnly:
          description: Creation date in datetime-only format
          required: false
          type: datetime-only
          example: 2017-10-04T14:54:36
        dateTime:
          description: Creation date in Zoned RFC3339 Date-time format
          required: false
          type: datetime
          format: rfc3339
          example: 2017-10-04T14:54:36Z
        dateTime2616:
          description: Zoned RFC2616 Date-time param example
          required: false
          type: datetime
          format: rfc2616
          example: Wed, 4 Jul 2001 12:08:56 PDT
        date:
          description: Date-only param example
          required: false
          type: date-only
          example: 2017-10-04
        time:
          description: time-only param example
          required: false
          type: time-only
        cardHolderAddress:
          description: return all payment card infomation
          type: Address
          required: false
      responses:
        200:
          body:
            application/json:
              type: common.PaymentCards
              examples:
               example: !include examples/body/paymentcards-get.json
            text/csv:
            application/xml: