#%RAML 1.0

title: ACME Banking HTTP API
version: 1.0
mediaType: application/json

uses:
  shapes: ./dataTypes/shapes.raml

traits:
  contentCacheable: !include traits/content-cacheable.raml

resourceTypes: 
  collection: !include resourceTypes/collection.raml
  member: !include resourceTypes/member.raml

types:
  CustomerMemberResponse: shapes.OrganizationData | shapes.PersonData

securitySchemes:
  oauth2_0: !include securitySchemes/oauth2_0.raml
  
securedBy: oauth2_0

/customers:
  displayName: Customer Resource
  /corporate:
    post:
      description: Customer data created correctly for an Organization
      body: shapes.NewOrganizationData
  /commercial:
    post:
      description: Customer data created correctly for a Person
      body: shapes.NewPersonData

  /{customer_id}:
    type:
      member:
        get-response-type: CustomerMemberResponse
        get-response-example: 
          type: Person
          id: "!23456"
          lei: 54930084UKLVMY22DS16
          tax_id: "999999999"
          email: info@new.org
          given_name: Dirk
          family_name: Fabian
          gender: male
          birth_date: 1987-09-30
          address:
            address_country: US
            address_locality: CA
            postal_code: "90003"
        patch-response-type: shapes.CustomerPatchData
    uriParameters:
      customer_id: string
    patch:
    delete:
    /accounts:
      type: 
        collection:
          response-type: shapes.BankAccountData
          request-type: shapes.NewBankAccountRequestData
      /{account_id}:
        type:
          member:
            get-response-type: shapes.BankAccountData
            get-response-example:
              id: my_account
              account_number: "12345667"
              accountType: standard
              amount: 
                value: 123.45
                currency: Euro
              lei: 54930084UKLVMY22DS16
              fees_and_comissions: no fees
              review_state: opened
              interest_rate: 12
              annual_interest_rate: 15
              minimum_inflow: 
                value: 1000
                currency: Euro
              overdraft_limit: 
                value: 500
                currency: Euro
        uriParameters:
          account_id: string
        delete:
    /loans:
      type: 
        collection:
          response-type: shapes.LoanData
          request-type: shapes.NewLoanRequestData
      get:
        is: [ contentCacheable ]
      /{loan_id}:
        type:
          member:
            get-response-type: shapes.LoanData
            get-response-example:
              id: my_account
              account_number: "12345667"
              accountType: standard
              amount: 
                value: 500
                currency: Euro
              lei: 54930084UKLVMY22DS16
              fees_and_comissions: no fees
              review_state: opened
              interest_rate: 12
              annual_interest_rate: 15
              minimum_inflow: 
                value: 500
                currency: Euro
              overdraft_limit: 
                value: 500
                currency: Euro
              grace_period: 
                value: 12m
        uriParameters:
          loan_id: string
      /schedule:
        get:
          description: Returns the repayments schedule for a Loan
          responses:
            200:
              body: shapes.RepaymentSpecificationData
    /cards:
      /debit:
        type: 
          collection:
            response-type: shapes.DebitCardData
            request-type: shapes.NewDebitCardRequestData
        /{card_id}:
          type:
            member:
              get-response-type: shapes.DebitCardData
              get-response-example:
                id: my_account 
                lei: 54930084UKLVMY22DS16
                fees_and_comissions: no fees
                review_state: opened
                cash_back: true
                contactless: false
                floor_limit: 
                  value: 500
                  currency: Euro
          uriParameters:
            card_id: string
          delete:
      /credit:
        type: 
          collection:
            response-type: shapes.CreditCardData
            request-type: shapes.NewCreditCardRequestData
        /{card_id}:
          type:
            member:
              get-response-type:  shapes.CreditCardData
              get-response-example:
                id: my_account
                amount: 
                  value: 500
                  currency: Euro
                lei: 54930084UKLVMY22DS16
                cash_back: true
                contactless: true
                floor_limit: 
                  value: 500
                  currency: Euro
                fees_and_comissions: no fees
                review_state: opened
                interest_rate: 12
                annual_interest_rate: 15
                minimum_inflow: 
                  value: 500
                  currency: Euro
                overdraft_limit: 
                  value: 500
                  currency: Euro
                grace_period: 
                  value: 12m
          uriParameters:
            card_id: string
          delete: