#%RAML 1.0
title: BigDecimalTest
version: v1
baseUri: "{version}"
mediaType:  application/json
types:
  BigDecimalWrapper: !include schemas/big-decimal-wrapper.json
/getBigDecimals:
  displayName: getBigDecimals
  get:
    responses:
      200:
        body:
          type: BigDecimalWrapper
