#%RAML 1.0
---
title: Contacts
version: v1
baseUri: "{version}"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]

/contacts:
  description: Endpoint to manipulate contacts
  displayName: Contacts
  get:
    description: Retrieve all contacts
    responses:
      200:
        description: Array containing all contacts
        body:
          application/json:
            schema: !include schemas-contacts/contacts.json
  /{id}:
    displayName: Contact
    get:
      description: Retrieve contact by id
      displayName: GetContactById
      responses:
        200:
          description: Single contact
          body:
            application/json:
              schema: !include schemas-contacts/contact.json
  /address:
    post:
      body:
        application/json:
          schema: !include schemas-contacts/address.json
      responses:
        200:
          body:
            application/json:
              schema: !include schemas-contacts/address.json
