#%RAML 1.0
---
#===============================================================
#  DataAccessGroup - RAML example http://raml.org/
#  References:
#    - RAML Specification - https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md
#===============================================================
title: AccessControl
version: v1
baseUri: "{version}"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
types:
  DataAccessGroup: !include schemas/dataaccessgroup-item.json
  BadRequest: !include schemas/bad-request.json
  InternalServerError: !include schemas/internal-server-error.json
#===============================================================
#  API documentation - Overall documentation.
#===============================================================
documentation:
  - title: AccessControl
    content: !include docs/api.md
#===============================================================
# API resource definitions
#===============================================================
/accesscontrol/accessgroups/data:
  description: save and update data access groups in the backbase platform for given type, subtype and legal entity id.
  displayName: DataAccessGroups
  uriParameters: null
  post:
    description: "save data access groups of type {type} and subtype {subtype} for given legal entity."
    body:
       application/json:
         type: DataAccessGroup
    responses:
      200:
        description: "New Data Access Group created successfully."
      400:
        description: BadRequest
        body:
          application/json:
            type: BadRequest
      500:
        description: InternalServerError
        body:
          application/json:
            type: InternalServerError
  put:
    description: "Update a data access group"
    queryParameters:
    body:
      application/json:
        type: DataAccessGroup
    responses:
      200:
        description:  "Data Access group updated successfully."
      400:
        description: BadRequest
        body:
          application/json:
            type: BadRequest
      500:
        description: InternalServerError
        body:
          application/json:
            type: InternalServerError