#%RAML 1.0
---
#===============================================================
#  AccessGroups - RAML example http://raml.org/
#  References:
#    - RAML Specification - https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md
#===============================================================
title: AccessGroups
version: v2
baseUri: "{version}"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
annotationTypes:
  deprecated: nil
types:
  ServiceAgreementItem: !include schemas/service-agreement-item.json
#===============================================================
# API resource definitions
#===============================================================
/accessgroups/serviceagreements:
  /{serviceAgreementId}:
    displayName: ServiceAgreementItem
    uriParameters:
      serviceAgreementId:
        displayName: Service Agreement ID
        type: string
        required: true
    get:
      queryParameters:
        type:
          displayName: type
          type: string
          description: Example Type
          example: Type
          required: false
          default: Type
      responses:
        200:
          description: "Service Agreement with given ID retrieved successfully."
          body:
            application/json:
              type: ServiceAgreementItem
              example: !include examples/service-agreement-item-ex.json
    /participants:
      displayName: ServiceAgreementParticipants
      get:
        queryParameters:
        responses:
          200:
            description: "Service Agreement participants retrieved successfully."
            body: 
              application/json:
                type: ServiceAgreementItem
                example: !include examples/service-agreement-item-ex.json
  /context:
    displayName: ServiceAgreementItem
    get:
      queryParameters:
        type:
          displayName: type
          type: string
          description: Example Type
          example: Type
          required: false
          default: Type
        foo:
          type: integer
          required: true
          example: 42
      responses:
        200:
          description: "Service Agreement for context retrieved successfully."
          body:
            application/json:
              type: ServiceAgreementItem
              example: !include examples/service-agreement-item-ex.json
    /participants:
      displayName: ServiceAgreementParticipants
      get:
        queryParameters:
        responses:
          200:
            description: "Service Agreement participants retrieved successfully."
            body:
              application/json:
                type: ServiceAgreementItem
                example: !include examples/service-agreement-item-ex.json
  /third-conflict:
    displayName: ServiceAgreementItem
    get:
      queryParameters:
        foo:
          type: integer
          required: true
          example: 42
      responses:
        200:
          description: "Service Agreement for context retrieved successfully."
          body:
            application/json:
              type: ServiceAgreementItem
              example: !include examples/service-agreement-item-ex.json
