#%RAML 1.0
---
title: Message Center
version: v1
baseUri: "{version}/messages"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
#===============================================================
# API resource definitions
#===============================================================
/users:
  displayName: Messages
  /{userId}:
    displayName: User
    get:
      responses:
        200:
          description: "User"
    /drafts:
      displayName: Drafts
      post:
        description: "Create a draft."
        responses:
          200:
            description: "Create a draft."