#%RAML 1.0
---
#===============================================================
#  Messages - RAML example http://raml.org/
#  References:
#    - RAML Specification - https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md
#===============================================================
title: AuditNonWhiteListed
version: v1
baseUri: "{version}/"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
#===============================================================
#  API documentation - Overall documentation.
#===============================================================
# API resource definitions
#===============================================================
/audit-messages:
  displayName: AuditNonWhiteListed
  get:
    description: Returns list of audit messages
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/accounts-get.json
          application/pdf:
          text/csv:
          application/xml:
