#%RAML 1.0
---
title: Functional Access Groups
version: v1
baseUri: "{version}"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
types:
  FunctionAccessGroupItem: !include schemas-nested/functionaccessgroup-item.json

/accessgroups:
  description: Endpoint to get functional access groups
  displayName: FunctionalAccessGroups
  get:
    description: Retrieve all functional access groups
    responses:
      200:
        description: 5-deep nested schemas
        body:
          application/json:
            type: FunctionAccessGroupItem
            example: !include functionaccessgroup-examples/functionaccessgroup-item.json
