#%RAML 1.0
---
#===============================================================
# Extends example
#===============================================================
title: Example
version: v1
baseUri: "{version}/test"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
schemas:
#===============================================================
#  API documentation - Overall documentation.
#===============================================================
documentation:
  - title: Example
    content: Test Schema to test extends keyword

#===============================================================
# API resource definitions
#===============================================================
/items:
  description: Retrieve items.
  displayName: items
  uriParameters: null
  get:
    description: "Retrieve item."
    queryParameters:
      param1:
        displayName: parameter1
        type: number
        description: Example Parameter
        example: 5
        required: false
    responses:
      200:
        description: Test Schema
        body:
          application/json:
            schema: !include schemas-extends/test-extends-item2.json
