#%RAML 1.0
---
#===============================================================
# Example which tests query and uri parameter scala types
#===============================================================
title: Example
uses:
  traits: traits/traits.raml
version: v1
baseUri: "{version}/test"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
#===============================================================
#  API documentation - Overall documentation.
#===============================================================
documentation:
  - title: Example
    content: Test Schema to test all common types

#===============================================================
# API resource definitions
#===============================================================
/items:
  description: Retrieve all items.
  displayName: items
  get:
    description: "Retrieve list of all items."
    queryParameters:
      stringParam:
        displayName: stringParam
        type: string
        description: Example String
        example: Hello World
        required: true
        default: Hello World
    responses:
      200:
        description: Test Schema
        body:
          application/json:
            schema: !include schemas/test-item.json
            example: !include examples/example-item.json
  put:
    description: "Update an item"
    queryParameters:
      stringParam:
        displayName: stringParam
        type: string
        description: Example String
        example: Hello World
        required: false
        default: Hello World
    responses:
      200:
        description: Test Schema
        body:
          application/json:
            schema: !include schemas/test-item.json
            example: !include examples/example-item.json
  post:
    description: "Delete an item"
    body:
       application/json:
          schema: !include schemas/test-item.json
          example: !include examples/example-item.json
    responses:
      204:
