#%RAML 1.0
---
#===============================================================
# API example which uses common.raml libary
#===============================================================
title: Example
uses:
  common: common.raml
version: v1
baseUri: "{version}"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
#===============================================================
#  API documentation - Overall documentation.
#===============================================================
documentation:
  - title: Example
    content: Test Schema to test a client-api
#===============================================================
# API resource definitions
#===============================================================
/types-two:
  description: Retrieve all items.
  displayName: fromtypesTwo
  uriParameters: null
  get:
    description: "Retrieve list of all items."
    responses:
      200:
        description: Test Schema
        body:
          application/json:
            type: common.MyType
/schema-two:
  description: Retrieve all items.
  displayName: fromschemaTwo
  uriParameters: null
  get:
    description: "Retrieve list of all items."
    responses:
      200:
        description: Test Schema
        body:
          application/json:
            type: common.MySchemaType