#%RAML 1.0
---
#===============================================================
# Trait example
#===============================================================
title: Example
version: v1
baseUri: "{version}/test"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
#===============================================================
#  API documentation - Overall documentation.
#===============================================================
documentation:
  - title: Example
    content: Test Schema to test item.json not having a type property.

#===============================================================
# API resource definitions
#===============================================================
/items:
  description: Retrieve all items.
  displayName: items
  uriParameters: null
  get:
    description: "Retrieve list of all items."
    queryParameters:
      param1:
        displayName: parameter1
        type: number
        description: Example Parameter
        example: 5
        required: false
    responses:
      200:
        description: Test Schema
        body:
          application/json:
            schema: !include test-get.json
            example: !include examples/example-get.json