openapi: 3.0.1
info:
  title: Example
  description: |
    # Example
    Test Schema to test an integration-api
  version: v1
servers:
- url: /serviceName/integration-api/v1
  description: The server
tags:
- name: example
paths:
  /items:
    summary: items
    description: Retrieve all items.
    get:
      tags:
      - items
      summary: Retrieve list of all items.
      description: Retrieve list of all items.
      operationId: getItems
      responses:
        "200":
          description: Test Schema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemsGetResponseBody'
              examples:
                example:
                  value: |-
                    {
                      "name" : "Example",
                      "description" : "Example description"
                    }
components:
  schemas:
    ItemsGetResponseBody:
      required:
      - name
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      description: this models a simple item.
      example:
        name: Example
        description: Example description
