name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  correct_repository:
    runs-on: ubuntu-latest
    steps:
    - name: fail on fork
      if: github.repository_owner != 'Backbase'
      run: exit 1

  update_release_draft:
    needs: correct_repository
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@3a7fb5c85b80b1dda66e1ccb94009adbbd32fce3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}