name: Find secrets

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: wget
      uses: wei/wget@c15e476d1463f4936cb54f882170d9d631f1aba5
      with:
        args: -O .rules.toml https://raw.githubusercontent.com/fnxpt/gitleaks-action/rules/.rules.toml
    - name: gitleaks-action
      uses: gitleaks/gitleaks-action@e87a89192a7a58b06bdedf25ad4196f89a45d76d
      with:
        config-path: .rules.toml
