name: Find secrets

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: wget
      uses: wei/wget@c15e476d1463f4936cb54f882170d9d631f1aba5
      with:
        args: -O .rules.toml https://raw.githubusercontent.com/fnxpt/gitleaks-action/rules/.rules.toml
    - name: gitleaks-action
      uses: gitleaks/gitleaks-action@bcfb9cce635345aac9996cedc19b2de8e01b894f
      with:
        config-path: .rules.toml
