name: Find secrets

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: wget
      uses: wei/wget@c15e476d1463f4936cb54f882170d9d631f1aba5
      with:
        args: -O .rules.toml https://raw.githubusercontent.com/fnxpt/gitleaks-action/rules/.rules.toml
    - name: gitleaks-action
      uses: gitleaks/gitleaks-action@961680e5305a30eb575f3ddf6bb6b2e265b68f0a
      with:
        config-path: .rules.toml
